#!/bin/bash
read -p "Input Number :" num
if [[ num -gt 10 ]]
then
	echo "Entered Number $num is greater than 10"
	if (( $num % 2 == 0 ))
	then
		echo " The number is also even number "
	else
		echo " The number is also odd number "
	fi
else
	echo " Entered Number is not bigger than 10 "
fi
