#!/bin/bash
read x
read y
read z
if [[ $x == $y ]] && [[ $x == $z ]]
then
	echo "EQUILATERAL"
elif [[ $x == $y ]] && [[ $y != $z ]]
then
	echo "ISOSCELES"
elif [[ $x == $z ]] && [[ $x != $y ]]
then
	echo "ISOSCELES"
elif [[ $y == $z ]] && [[ $y != $x ]]
then
	echo "ISOSCELES"
else
	echo "SCALENE"
fi
