#!/bin/bash
while read line
do 
  for i in $line
  do
    echo $((i**2))
  done
  read -p " To Quit press y/n: " letter
  if [[ $letter == y ]]
  then
  exit
  else
    echo "Lets play again..."
  fi
done